name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - numpy=1.16.4
  - descartes
  - geopandas
  - rasterio
  - python-slugify
  - tqdm
  - laspy
  - lastools
  - laszip
  - pip
    - detectree
    - -e .
