name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - contextily
  - descartes
  - geopandas
  - laspy
  - lastools
  - laszip
  - matplotlib
  - numpy=1.16.4  
  - osmnx>=0.15
  - python-slugify  
  - pip
  - pip:
    - detectree
    - -e .
  - rasterio
  - shapely
