name: detectree
channels:
  - conda-forge
dependencies:
  - click
  - numpy=1.16.4
  - descartes
  - geopandas
  - laspy
  - lastools
  - laszip
  - python-slugify  
  - pip
  - pip:
    - detectree
    - -e .
